# Question 2

import tkinter as tk
window = tk.Tk()
window.title("resgisteration form")
window.configure(bg='light green')
heading = tk.Label(window, text="Form", font=("Arial", 12), bg='light green',
justify='center')
heading.grid(row=0, column=0, columnspan=2)
tk.Label(window, text="Name ", bg='light green').grid(row=1, column=0)
name = tk.Entry(window, width=50)
name.grid(row=1, column=1)
tk.Label(window, text="Course ", bg='light green').grid(row=2, column=0)
course = tk.Entry(window, width=50)
course.grid(row=2, column=1)
tk.Label(window, text="Semester ", bg='light green').grid(row=3, column=0)
semester = tk.Entry(window, width=50)
semester.grid(row=3, column=1)
tk.Label(window, text="Form No. ", bg='light green').grid(row=4, column=0)
form_no = tk.Entry(window, width=50)
form_no.grid(row=4, column=1)
tk.Label(window, text="Contact No. ", bg='light green').grid(row=5, column=0)
contact_no = tk.Entry(window, width=50)
contact_no.grid(row=5, column=1)
tk.Label(window, text="Email ID ", bg='light green').grid(row=6, column=0)
email_id = tk.Entry(window, width=50)
email_id.grid(row=6, column=1)
tk.Label(window, text="Address ", bg='light green').grid(row=7, column=0)
address = tk.Entry(window, width=50)
address.grid(row=7, column=1)
def submit_form():
    name_data = name.get()
    course_data = course.get()
    semester_data = semester.get()
    form_no_data = form_no.get()
    contact_no_data = contact_no.get()
    email_id_data = email_id.get()
    address_data = address.get()
    print("Name:", name_data)
    print("Course:", course_data)
    print("Semester:", semester_data)
    print("Form No.:", form_no_data)
    print("Contact No.:", contact_no_data)
    print("Email ID:", email_id_data)
    print("Address:", address_data)
submit_btn = tk.Button(window, text="Submit", bg='red', command=submit_form)
submit_btn.grid(row=8, column=1)
window.mainloop()
