# Question 3

import tkinter as tk
root = tk.Tk()
root.geometry("400x300")
root.title("Address Entry Form")
def submit_form():
    first_name = label_first_name.get()
    last_name = label_last_name.get()
    address_line_1 = label_address1.get()
    address_line_2 = label_address2.get()
    city = label_city.get()
    state = label_state.get()
    postal_code = label_postal_code.get()
    country = label_country.get()
    print("First Name:", first_name)
    print("Last Name:", last_name)
    print("Address Line 1:", address_line_1)
    print("Address Line 2:", address_line_2)
    print("City:", city)
    print("State/Province:", state)
    print("Postal Code:", postal_code)
    print("Country:", country)
def clear_form():
    label_first_name.delete(0, tk.END)
    label_last_name.delete(0, tk.END)
    label_address1.delete(0, tk.END)
    label_address2.delete(0, tk.END)
    label_city.delete(0, tk.END)
    label_state.delete(0, tk.END)
    label_postal_code.delete(0, tk.END)
    label_country.delete(0, tk.END)
label_first_name = tk.Label(root, text="First Name:")
label_last_name = tk.Label(root, text="Last Name:")
label_address1 = tk.Label(root, text="Address Line 1:")
label_address2 = tk.Label(root, text="Address Line 2:")
label_city = tk.Label(root, text="City:")
label_state = tk.Label(root, text="State/Province:")
label_postal_code = tk.Label(root, text="Postal Code:")
label_country = tk.Label(root, text="Country:")
entry_first_name = tk.Entry(root,width=50)
entry_last_name = tk.Entry(root,width=50)
entry_address1 = tk.Entry(root,width=50)
entry_address2 = tk.Entry(root,width=50)
entry_city = tk.Entry(root,width=50)
entry_state = tk.Entry(root,width=50)
entry_postal_code = tk.Entry(root,width=50)
entry_country = tk.Entry(root,width=50)
label_first_name.grid(row=0, column=0)
entry_first_name.grid(row=0, column=1)
label_last_name.grid(row=1, column=0)
entry_last_name.grid(row=1, column=1)
label_address1.grid(row=2, column=0)
entry_address1.grid(row=2, column=1)
label_address2.grid(row=3, column=0)
entry_address2.grid(row=3, column=1)
label_city.grid(row=4, column=0)
entry_city.grid(row=4, column=1)
label_state.grid(row=5, column=0)
entry_state.grid(row=5, column=1)
label_postal_code.grid(row=6, column=0)
entry_postal_code.grid(row=6, column=1)
label_country.grid(row=7, column=0)
entry_country.grid(row=7, column=1)
button_clear = tk.Button(root, text="Clear")
button_submit = tk.Button(root, text="Submit")
button_clear.grid(row=8, column=0,columnspan=2)
button_submit.grid(row=8, column=1)
root.mainloop()
