# Question 4

import tkinter as tk
root = tk.Tk()
root.title("Personal Information and Address Entry Form")
personal_info_frame = tk.LabelFrame(root, text="Personal Information", padx=10,
pady=10)
personal_info_frame.grid(row=0, column=0, padx=10, pady=10, sticky="nsew")
first_name_label = tk.Label(personal_info_frame, text="First Name")
first_name_label.grid(row=0, column=0, padx=5, pady=5, sticky="w")
first_name_entry = tk.Entry(personal_info_frame)
first_name_entry.grid(row=0, column=1, padx=5, pady=5)
last_name_label = tk.Label(personal_info_frame, text="Last Name")
last_name_label.grid(row=1, column=0, padx=5, pady=5, sticky="w")
last_name_entry = tk.Entry(personal_info_frame)
last_name_entry.grid(row=1, column=1, padx=5, pady=5)
address_frame = tk.LabelFrame(root, text="Address", padx=10, pady=10)
address_frame.grid(row=1, column=0, padx=10, pady=10, sticky="nsew")
street_label = tk.Label(address_frame, text="Street")
street_label.grid(row=0, column=0, padx=5, pady=5, sticky="w")
street_entry = tk.Entry(address_frame)
street_entry.grid(row=0, column=1, padx=5, pady=5)
city_label = tk.Label(address_frame, text="City")
city_label.grid(row=1, column=0, padx=5, pady=5, sticky="w")
city_entry = tk.Entry(address_frame)
city_entry.grid(row=1, column=1, padx=5, pady=5)
zip_label = tk.Label(address_frame, text="ZIP Code")
zip_label.grid(row=2, column=0, padx=5, pady=5, sticky="w")
zip_entry = tk.Entry(address_frame)
zip_entry.grid(row=2, column=1, padx=5, pady=5)
def submit():
    first_name = first_name_entry.get()
    last_name = last_name_entry.get()
    street = street_entry.get()
    city = city_entry.get()
    zip_code = zip_entry.get()
    print(f"Name: {first_name} {last_name}")
    print(f"Address: {street}, {city}, {zip_code}")
submit_button = tk.Button(root, text="Submit", command=submit)
submit_button.grid(row=2, column=0, padx=10, pady=10)
def clear():
    first_name_entry.delete(0, tk.END)
    last_name_entry.delete(0, tk.END)
    street_entry.delete(0, tk.END)
    city_entry.delete(0, tk.END)
    zip_entry.delete(0, tk.END)
clear_button = tk.Button(root, text="Clear", command=clear)
clear_button.grid(row=2, column=1, padx=10, pady=10)
root.mainloop()
